# 配置文件
# Configuration file for mcp_server_aom
service_code: cbh
transport: http  # 支持 stdio, http 和  sse
port: 8009 # http 和 sse 模式需要设定端口


 # Configuration file for mcp_server_asm
# Configuration file for mcp_server_bms
