# Configuration file for mcp_server_aom
service_code: bms
transport: http  # 支持 stdio, http 和  sse
port: 8007 # http 和 sse 模式需要设定端口


 # Configuration file for mcp_server_asm
# Configuration file for mcp_server_bms
